export const SAVE_ORDER_ITEMS = 'SAVE_ORDER_ITEMS';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';

export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'

export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';

export const SET_ORDER_TO_NULL = 'SET_ORDER_TO_NULL';